server:
  port: 8081
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /mybatis

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root

  thymeleaf:
    cache: false
    mode: LEGACYHTML5

  redis:
      # Redis数据库索引（默认为0）
      database: 0
      # Redis服务器地址
      host: localhost
      # Redis服务器连接端口
      port: 6379
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
      # 连接超时时间（毫秒）
        timeout: 10000

mybatis:
  type-aliases-package: com.kyrie.mybatis.entity
  mapper-locations: classpath:mapper/*.xml




logging:
  level:
    com:
      kyrie:
        mybatis:
          mapper: debug
