server:
  port: 8081
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /mybatis

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root

  thymeleaf:
    cache: false
    mode: LEGACYHTML5

mybatis:
  type-aliases-package: com.kyrie.mybatis.entity
  mapper-locations: classpath:mapper/*.xml