server:
  port: 8030
  servlet:
    context-path: /kyrie



spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/write?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource



mybatis:
  type-aliases-package: com.kyrie.write.entity
  mapper-locations: classpath:mapper/*.xml